# Generated by Django 5.1 on 2024-09-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosko_tecnologico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='contacto',
            new_name='direccion',
        ),
    ]
