# Generated by Django 5.1 on 2024-09-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosko_tecnologico', '0002_rename_contacto_proveedor_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ManyToManyField(to='kiosko_tecnologico.producto'),
        ),
    ]
