# Generated by Django 5.1 on 2024-09-22 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosko_tecnologico', '0004_remove_venta_producto_producto_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosko_tecnologico.producto'),
        ),
    ]
