# Generated by Django 5.1 on 2024-09-23 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosko_tecnologico', '0006_remove_venta_producto_venta_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosko_tecnologico.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosko_tecnologico.venta')),
            ],
        ),
        migrations.DeleteModel(
            name='DetalleProducto',
        ),
    ]
