# Generated by Django 5.1 on 2024-09-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosko_tecnologico', '0007_remove_venta_cantidad_remove_venta_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
