# Generated by Django 5.1 on 2024-09-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosko_tecnologico', '0008_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
