# Generated by Django 5.1 on 2024-09-28 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosko_tecnologico', '0009_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosko_tecnologico.cliente')),
                ('productos', models.ManyToManyField(to='kiosko_tecnologico.producto')),
            ],
        ),
    ]
