# Generated by Django 5.1 on 2024-09-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosko_tecnologico', '0011_remove_detalleventa_venta_remove_factura_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(through='kiosko_tecnologico.DetalleVenta', to='kiosko_tecnologico.producto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
